### ISSUE TITLE
Update pickr to 0.4.9

### ISSUE THREAD

**Issue by elgordino** [astronomersiva/ember-pickr#10]
pickr 0.4.9 contains fixes for positioning the pickr in scrolled and transformed views. Could ember-picker be updated to use this latest version?

Thanks!

**Comment by astronomersiva** [comment]
Hello @elgordino!

I have created a [PR](https://github.com/astronomersiva/ember-pickr/pull/11/files) to do this. pickr has undergone significant changes and the tests had to be updated. When doing that I got suspicions of memory leaks being possible due the new design that allows scrolling when the picker is open.

Here's a GIF that demonstrates how DOM elements keep building up even though the component instances that created them have themselves been destroyed.

![possibleMemLeak](https://user-images.githubusercontent.com/7725225/56226367-afa69d80-6090-11e9-88e3-238985af1839.gif)

As a result, the event listeners associated with them are also active.

<img width="369" alt="event listeners" src="https://user-images.githubusercontent.com/7725225/56226723-7d497000-6091-11e9-8ea5-91421878d752.png">

I would need to look into this patiently and try and fix as much as possible upstream. This might take a few days. In the meantime, if the upstream changes are critical to you, I would suggest using the GitHub branch link of the PR that I linked in your package.json.

**Comment by astronomersiva** [comment]
I have created a [PR upstream](https://github.com/Simonwep/pickr/pull/84) to fix these issues. Will release the changes here once it gets merged.

**Comment by Simonwep** [comment]
I've merged it and published 0.4.10 where, thanks to @astronomersiva 's, clean up is done ~more~ properly. `palette` got completely optional (just swatches are now possible) and `defaultRepresentation` is now more robust.

**Comment by astronomersiva** [comment]
Released v1.2.3 with relevant changes.

**Comment by elgordino** [comment]
Thank you very much @astronomersiva @Simonwep
