### ISSUE TITLE
Outdated pickr dependency

### ISSUE THREAD

**Issue by makepanic** [astronomersiva/ember-pickr#59]
Hi, great addon.

I was looking into how to change the pickr theme but noticed that this addon uses `pickr@0.4.10` but the latest upstream version is [1.2.2](https://github.com/Simonwep/pickr/tree/1.2.2).

Would you be interested in upgrading pickr to get various fixes and features?

I could try to create a PR for this. There's the question how to make the theme configurable for addon consumers though. For now it's probably good enough to let them manually `  app.import("node_modules/@simonwep/pickr/dist/themes/nano.min.css");` until this addon finds a better way.

Nvm we should probably make it configurable and use the classic theme by default.

**Comment by astronomersiva** [comment]
Hi, there are several huge breaking changes between 0.4 and 0.6 that's blocking this. Let me take a stab at this over the weekend

**Comment by makepanic** [comment]
I already started working on getting it to run on 1.2.2. 
The only real issue i found was the unsupported `middle` position.

**Comment by astronomersiva** [comment]
That's interesting. Can you raise a PR?

**Comment by makepanic** [comment]
Created a PR at https://github.com/astronomersiva/ember-pickr/pull/60
