### ISSUE TITLE
cancel event is swallowed

### ISSUE THREAD

**Issue by makepanic** [astronomersiva/ember-pickr#62]
`pickr` emits a [cancel event](https://github.com/Simonwep/pickr#events) when clicking the cancel button.

Sadly this isn't handled/proxied by ember-pickr.
I think it would be great to allow consumers to do something on cancel.

Oops seems like cancel and clear were added 22hrs ago in a release:

https://github.com/Simonwep/pickr/releases/tag/1.2.3

I'll create a PR to add support for these

**Comment by astronomersiva** [comment]
haha, I was about to comment that after seeing the email notification 😆 Thanks for the quick PR though!
