### ISSUE TITLE
Error in Edge Ember-cli from ember-pickr because of spread operator

### ISSUE THREAD

**Issue by Benjy1979** [astronomersiva/ember-pickr#71]
![error](https://user-images.githubusercontent.com/5563332/62112470-aee5f000-b2aa-11e9-872e-91488648f96a.png)
This attached line throws an error in Edge when running locally.

**Comment by astronomersiva** [comment]
I believe this is because object spread isn't supported in Edge yet. However, this must be handled by transpilation. Can you check if `Edge` is present in your browser targets?

**Comment by astronomersiva** [comment]
@Benjy1979, were you able to address this by adding `Edge` to the browser targets?

**Comment by Benjy1979** [comment]
Yes, thanks that did it. I wasn't aware of this feature in Ember - ignorance

**Comment by astronomersiva** [comment]
No issues @Benjy1979, do let me know if you face any further issues. Will be happy to help out.
