### ISSUE TITLE
Allow default color null

### ISSUE THREAD

**Issue by gbrlmrllo** [astronomersiva/ember-pickr#72]
I think there should be the possibility of default color as null.

**Comment by yemartin** [comment]
I just hit this requirement too.

The author of Pickr explains in [this comment](https://github.com/Simonwep/pickr/issues/140#issuecomment-524312261) why he thinks `default: null` is an anti-feature in his view. The gist of it is:

> Which color should be chosen if the user opens pickr?

Now, there is a use case for starting Pickr with no color selected (a.k.a. the "`clear`" state). And the author says you can achieve this by calling `setColor(null)` inside the `init` event. But unfortunately, `ember-pickr` does not give us access to that event. So we are stuck now...

I propose 3 solutions:

A) Add an `initial:` option, to set the initially selected color, separately from the default color. The problem with this: it does not make sense to have both initial and default set...

B) Add a `startCleared` option (better names welcome).

C) Add an `onInit` handler, that would get passed the Pickr instance.

What do you think?

**Comment by astronomersiva** [comment]
I have released `2.2.1` that supports the `onInit` hook.  I have also added an example for setting `null` in the [docs](https://astronomersiva.github.io/ember-pickr/docs/).

Please feel free to reopen this issue if there are further concerns.

**Comment by yemartin** [comment]
Awesome! And thanks a lot for the blazing fast response @astronomersiva ! I am putting this to good use right away.

**Comment by gbrlmrllo** [comment]
Awesome! It worked perfectly for me, thanks for this fix @astronomersiva 🎉
